# Generated by Django 6.0.3 on 2026-03-31 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normal_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_processor', models.CharField(max_length=200)),
                ('product_ram', models.CharField(max_length=200)),
                ('product_generation', models.CharField(max_length=200)),
                ('product_storage', models.CharField(max_length=200)),
                ('product_graphics', models.CharField(max_length=200)),
                ('product_display', models.CharField(max_length=200)),
                ('all_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.normal_product')),
            ],
        ),
        migrations.CreateModel(
            name='Phone_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_display', models.IntegerField()),
                ('product_camera', models.CharField(max_length=100)),
                ('product_battery', models.CharField(max_length=200)),
                ('product_ram', models.CharField(max_length=200)),
                ('product_storage', models.CharField(max_length=200)),
                ('all_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.normal_product')),
            ],
        ),
    ]
