# Generated by Django 6.0.3 on 2026-04-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop_product',
            name='all_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.normal_product'),
        ),
        migrations.AlterField(
            model_name='phone_product',
            name='all_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.normal_product'),
        ),
    ]
